spring:
  datasource:
    url: jdbc:mysql://34.22.71.235:3306/shop?serverTimezone=UTC&characterEncoding=UTF-8 #34.22.71.235 고정 아님
    username: yaeeun #gcp-> yaeeun, localhost-> root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

server:
  port: 8080
  address: 0.0.0.0

